### PR TITLE
[FIX] Docker&conda interaction breaks singularity

### PR DESCRIPTION
**Pull request by oesteban**
Closes #651. Reference https://github.com/singularityware/singularity/issues/571

### CODE REVIEW

**Comment by effigies** [comment]
Out of curiosity, why is a `sync` at the end of the command insufficient?

**Comment by oesteban** [comment]
Because the lack of synchronization with the filesystem may happen at any point between conda commands. Actually, that `chmod +x /usr/local/miniconda/bin/*` was introduced for this very reason: we used to have a first conda install command to update the python version and a second call installing new packages. Without the chmod or the sync, this would fail with some frequency.

**Comment by effigies** [comment]
Haha, computers are awful.

I really thought the VFS was supposed to keep things consistent, even if the storage medium isn't synced. Is this a Docker failure to implement a VFS layer correctly?

Anyway, full-speed ahead, if this resolves the issues you're having. (I can't verify because I haven't experienced the problem.)

**Comment by oesteban** [comment]
I've seen these problems on my desktop using AUFS and on Circle (using BTRFS), so it must be some kind of "optimization" on conda that docker build does not like.

**Comment by effigies** [comment]
@oesteban Is this okay to merge?

**Comment by oesteban** [comment]
Yup

**Pull request merged**
