### PR TITLE
[RTM] minor bbregister option tweak

### PR DESCRIPTION
**Pull request by chrisfilo**

### CODE REVIEW

**Comment by chrisfilo** [comment]
Depends on https://github.com/nipy/nipype/pull/1929

**Comment by chrisfilo** [comment]
I've tested this on a couple of datasets. It seems to help with ds000114 without making any visible negative impact on the beast.

**Comment by chrisfilo** [comment]
FS6 is already a hard dependency - `-hires` does not work in 5.3 AFAIK. I would prefer to avoid adding a try catch for partial support of 5.3.

**Comment by effigies** [comment]
True. Maybe a note in the [External Dependencies](https://github.com/poldracklab/fmriprep/blob/master/docs/installation.rst#external-dependencies) section of `installation.rst`, then?

**Comment by chrisfilo** [comment]
https://github.com/poldracklab/fmriprep/pull/424

**Pull request merged**
