### PR TITLE
[RTM] ENH: Merge T1w images to unbiased template if N < 3 or --longitudinal is passed

### LINKED ISSUE #310: Support for multisession data with multiple T1s
In case the dataset includes multiple sessions **and** each session includes at least one T1w image the pipeline should default to coregistering EPI to the T1w image from the corresponding session.

Alternatively an **unbiased** subject specific template (combination of all T1w images from a given subject) should be created and set as the coregistration target.

Currently the pipeline defaults to combining all T1w images (even across sessions) by coregistering all of them to the first T1 found. This is acceptable for combining multiple T1w images from a single session, but results in a bias towards the first T1w and thus is suboptimal in context of longitudinal studies.

Creating unbiased structural templates is necessary for both the volume as well as surface analysis. Former can be achieved using ANTs or AFNI - latter is supported by the FreeSurfer longitudinal stream.

### PR DESCRIPTION
**Pull request by effigies**
Not running against CircleCI at this point because we'll need to test outside of CI against datasets with multiple T1w images before we merge this. This is a placeholder PR until then.

I'd also like to go ahead and use `mri_robust_register` to align any T2w images (see #474).

Note that this could break alignment between result images from previous FMRIPREP versions. Should probably be put into release notes.

Closes #310

### CODE REVIEW

**Comment by effigies** [comment]
This adds serious run time to the `t1_merge` node for ds031, which merges 9 T1w images (testing after rebasing on top of #601). We could make it an option (`--longitudinal`?) with a note that runtime may be increased.

Also, I think we can use OpenMP, so I'll give that a shot.

**Comment by chrisfilo** [comment]
how serious?

**Comment by effigies** [comment]
It's taken over half an hour. Before I think it took ~10min, but I'll run both versions tonight with less other things going on the system to get a difference.

Once I was sure it was a major slowdown, I killed it to try to play with OpenMP. Just to verify that it does actually parallelize.

**Comment by effigies** [comment]
For ds031/sub-01 (9 images):

Alignment | `OMP_NUM_THREADS` | Time
--|--|--
Aligning to first image| | 16m
Aligning to first image | 7 | 5m
Unbiased template|| 1h46m
Unbiased template | 7 | 1h21m

**Comment by effigies** [comment]
Re: ds031, it's unclear whether we'd get a better speed-up profile if the number of images matched the number of threads; it could be that the parallel sections are going from 9 to 2. But even if so, it looks like the serial component for constructing an unbiased template is ~74min, and maximum concurrency might bring us down to 77-78min.

Similarly, for a simple alignment, it looks like we have a serial section of ~2.5min with maximum concurrency reducing to 3.6-3.7min.

I would say it makes sense to parallelize to `min(num_images, omp_nthreads)`, which keeps small merges from eating up all the cores to little benefit, and to make unbiased templates optional. Given the low additional cost for a small number of input images, it could also make sense to make unbiased templates the default for fewer than N images (and I'll work out what a reasonable N is).

**Comment by chrisfilo** [comment]
That's really long! I agree with your suggestions.

**Comment by effigies** [comment]
Haha, wow. N=2. Going from 2 to 3 images increases from <2min to ~25min. I do not need to see the curve badly enough to keep going.

**Comment by effigies** [comment]
It's the stochastic ICA-AROMA bug. If it pops up again, I'll merge #611 before running another round of tests.

**Pull request merged**
