### PR TITLE
FIX: Set TemplateFlow directory world-writeable

### LINKED ISSUE #1500: TemplateFlow permissions error in 1.3.0
Relevant traceback:

```
  File "/usr/local/miniconda/lib/python3.7/site-packages/smriprep/workflows/anatomical.py", line 621, in init_skullstrip_ants_wf
    t1_skull_strip.inputs.brain_template = get_template(skull_strip_template, 'res-01_T1w.nii.gz')
  File "/usr/local/miniconda/lib/python3.7/site-packages/templateflow/api.py", line 24, in get
    out_file = api.get(filepath)
[...]
  File "/usr/local/miniconda/lib/python3.7/site-packages/datalad/cmd.py", line 530, in run
    raise CommandError(str(cmd), msg, status, out[0], out[1])
datalad.support.exceptions.CommandError: CommandError: command '['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'find', '--json', '--not', '--in', 'here', '--', 'tpl-OASIS30ANTs_res-01_T1w.nii.gz']' failed with exitcode 1
Failed to run ['git', '-c', 'receive.autogc=0', '-c', 'gc.auto=0', 'annex', 'find', '--json', '--not', '--in', 'here', '--', 'tpl-OASIS30ANTs_res-01_T1w.nii.gz'] under '/opt/templateflow/tpl-OASIS30ANTs'. Exit code=1. out= err=git-annex: .git/annex/journal.lck: openFd: permission denied (Permission denied)
```

My suspicion is that the solution would be to add `umask 000` before `datalad` commands in the Dockerfile.

Full [log](https://gist.github.com/Gilles86/75c3b848f1973d947f0838a1020f7f76).

cc @Gilles86 @oesteban

### PR DESCRIPTION
**Pull request by effigies**
## Changes proposed in this pull request

No real way to test this until merged, built and pushed to `poldracklab/fmriprep:unstable` to build a Singularity image off of.

Fixes #1500.

### CODE REVIEW

**Comment by oesteban** [comment]
Should we reset a more restrictive umask after templateflow is installed?

**Comment by effigies** [comment]
`umask` is local to the shell process. By my understanding, each `RUN` command is run in an independent shell. That's why Docker has `ENV a=b` instead of `RUN export a=b`.

**Comment by effigies** [comment]
Dockerfile:

```Dockerfile
FROM alpine:3.6

RUN umask
RUN umask 000 && umask
RUN umask
```

```Shell
$ docker build -t umask_test .
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM alpine:3.6
 ---> 77144d8c6bdc
Step 2/4 : RUN umask
 ---> Running in 621ee0185ae2
0022
Removing intermediate container 621ee0185ae2
 ---> 4e9d5b8e4b0c
Step 3/4 : RUN umask 000 && umask
 ---> Running in b64027ef68ce
0000
Removing intermediate container b64027ef68ce
 ---> f6839a900a24
Step 4/4 : RUN umask
 ---> Running in f0e2dab2abfc
0022
Removing intermediate container f0e2dab2abfc
 ---> 9e338df90910
Successfully built 9e338df90910
Successfully tagged umask_test:latest
```

**Comment by effigies** [comment]
Going to merge rather than wait forever on the anatomical workflows to recache.

**Pull request merged**
