### PR TITLE
[RTM] RF: Conform cleanup wf to naming conventions

### PR DESCRIPTION
**Pull request by effigies**
Minor change suggested by a look at the [ds054 graph](https://384-78558509-gh.circle-artifacts.com/0/home/ubuntu/ds054/scratch/fmriprep_wf/graph.dot.svg).

### CODE REVIEW

**Comment by effigies** [comment]
While we're at it, do we want to collapse the workflows in https://385-78558509-gh.circle-artifacts.com/0/home/ubuntu/docs/sdc/estimation.html and https://385-78558509-gh.circle-artifacts.com/0/home/ubuntu/docs/sdc/unwarping.html?

**Comment by chrisfilo** [comment]
What do you mean by collapsing? The graphs or the workflows themselves?

**Comment by effigies** [comment]
The graphs, so that workflows show up as single nodes in the graph, as we did for the `anat_preproc_wf` and `func_preproc_wf`.

**Comment by chrisfilo** [comment]
Ah yes - that's a good idea. I did not know how to do that with the docstrings thou.

**Comment by effigies** [comment]
I'll put together a quick PR.

**Pull request merged**
