### PR TITLE
added zenodo entry

### PR DESCRIPTION
**Pull request by chrisfilo**
@jdkent, @craigmoodie, @feilong, @erramuzpe, @zenkavi, @ilkayisik, @yarikoptic please post your pen names, affiliations and ORCID if you would like to be included as coauthors in the Zenodo entry for FMRIPREP.

### CODE REVIEW

**Comment by ilkayisik** [comment]
Hey Chris, 
Even though I also did not contribute in a great deal yet, I would be happy to be added as a contributor and would like to contribute even more in the future.
Here is my info:
Pen Name: Ayse Ilkay Isik
Affiliation: Max Planck Institute for Empirical Aesthetics
Orcid: http://orcid.org/0000-0002-1652-9297

**Comment by craigmoodie** [comment]
Hi Chris,

Thanks for the note. Here is my info:

Craig Moodie
Stanford University
orcid.org/0000-0003-0867-1469


Hope all is well!

Best,
Craig.

**Comment by feilong** [comment]
Thanks, here is my information:

Feilong Ma
Dartmouth College
0000-0002-6838-3971

**Comment by chrisfilo** [comment]
This should be ready to merge.

**Comment by effigies** [comment]
Sounds good. @jdkent, @erramuzpe, @zenkavi, if you want to be listed in Zenodo releases, please submit PRs updating this file. Looks like your entries should go just before Russ's.

**Pull request merged**
