### PR TITLE
CI: Use recent Python image to build packages

### PR DESCRIPTION
**Pull request by effigies**
## Changes proposed in this pull request

Switches to `circleci/python:3.7.4` for building packages on, as this should have a long lifetime before we need to upgrade it.

The latest twine breaks Python 3.5 but still installs on it, so our current strategy fails. We could pin an older twine, but there doesn't seem much value.

@oesteban I see we're still using manylinux to build wheels. I believe we no longer need that?

### CODE REVIEW

**Comment by oesteban** [comment]
> @oesteban I see we're still using manylinux to build wheels. I believe we no longer need that?

Probably not after this change :+1:

**Comment by effigies** [comment]
I looked, and it looks like we still have a cython extension. For some reason I thought that had gone with sdcflows.

**Comment by oesteban** [comment]
mmm yeah, that should be gone.

**Comment by effigies** [comment]
Okay. I'll open a PR to kill it shortly.

**Pull request merged**
