### PR TITLE
[FIX] Reduce image loads in local memory

### PR DESCRIPTION
**Pull request by effigies**
The goal of this PR is to systematically go through all nibabel image loads and image-data reads, and ensure that they do not happen in local memory. This is operating on the theory that there is a memory leak (or gc delay) in the "master" process, that is resulting in large `fork`ed processes, eventually causing crashes.

Minor cleanups while auditing.

Starting early so I can make comments as I find things that don't have obvious fixes.

### CODE REVIEW

**Comment by effigies** [comment]
This code is run in the master process. There's no good way I can see around loading at least some data from this file.

https://github.com/poldracklab/fmriprep/blob/23f82eb0d08375105c907b8a97d22bf2aa612d98/fmriprep/workflows/bold/base.py#L839-L848

One possibility would be to wrap this in a subprocess, as nipype does, to shield the master process from its memory usage. That seems like a lot of boilerplate. Pushing a post-build/pre-run GC collection, to hopefully reduce the impact of calls like this.

**Comment by effigies** [comment]
Audit complete. With the exception of the above function, I think all `nb.load` uses are now no longer being tagged with `run_without_submitting`, which I suspect is the biggest source of memory expansion during workflow runtime.

There could still be issues arising from nipype and niworkflows.

**Comment by effigies** [comment]
Also, trying to pad my "lines deleted" stats.

deletions

**Comment by oesteban** [comment]
Refs. #833

**Pull request merged**
