### PR TITLE
pin: sdcflows with niflows

### PR DESCRIPTION
**Pull request by mgxd**
## Changes proposed in this pull request

PIN sdcflows to account for nipype.workflows migration

### CODE REVIEW

**Comment by mgxd** [comment]
well, the signature of `init_sdc_wf()` has changed since the last release of sdcflows

@oesteban can you take a look when you have some time?

**Comment by effigies** [comment]
We could probably just pin the niflows in fMRIPrep, really. We'll probably want to suppress the warnings on import, to avoid getting a bunch of false alarm bug reports.

That's assuming the sdcflows fix isn't easy.

**Comment by oesteban** [comment]
I'll cut a new release based off the latest including the pin :+1:

**Comment by oesteban** [comment]
Closed via #1792

**Pull request closed without merging**
