### PR TITLE
ENH: load .bids_ignore file and feed it to pybids.BIDSLayout

### PR DESCRIPTION
**Pull request by bpinsard**
## Changes proposed in this pull request

Ignore files in `.bidsignore` (as it is not used by pybids for now).
Can be useful in cases where we use BIDS extension with entities which are not yet supported by pybids and thus cannot be used to filter the fmriprep input data.

Currently, it might not be able to deal with the full .gitignore syntax as it only uses `fnmatch`. For instance the `!` might not work.

Also, I can't remember why the `BIDSLayout` is created with `validate=False`? For lesion masks maybe?

## Documentation that should be reviewed

TODO.
Not sure in which part of the doc this should be documented.

### CODE REVIEW

**Comment by oesteban** [comment]
@effigies, shouldn't pyBIDS automatically pick up the `.bidsignore`?

**Comment by oesteban** [comment]
> Also, I can't remember why the `BIDSLayout` is created with `validate=False`? For lesion masks maybe?

I think so. Also because we rely on the user not setting `--skip-bids-validation`.

**Comment by oesteban** [comment]
> Not sure in which part of the doc this should be documented.

I think we may want to open a subsection under `docs/usage.rst` for the BIDS filters option.

**Comment by effigies** [comment]
Sorry, I missed this. No `.bidsignore` is a BIDS validator concept, and not a PyBIDS one. It is not inherent to BIDS. There have been discussions about merging it, but the problem is that there are two reasonable interpretations:

1. Do not index the ignored data; it's just here for completeness, and tools should not attempt to interpret unspecified data.
2. Ignore warnings on the ignored data; it's here to be used by a tool that knows to look for it.

**Review by mgxd — COMMENTED** [review]
Looking through this now, perhaps it makes more sense to leave non-standard layout initialization up to the user (using an already generated index of the layout with the newly added `--bids-database-dir` flag). Then, when https://github.com/bids-standard/pybids/pull/650 is merged, it will be much easier for users to generate custom layouts, such as adding `ignore` values.

**Comment by effigies** [comment]
Agreed. I don't think this is a productive way forward as it will make fMRIPrep behave very idiosyncratically relative to other BIDS Apps. Let's close this, and I will review the PyBIDS CLI PR...

**Pull request closed without merging**
