### PR TITLE
PIN: ``nilearn!=0.5.0,!=0.5.1`` to avoid problems plotting mgz images

### PR DESCRIPTION
**Pull request by oesteban**

### CODE REVIEW

**Comment by oesteban** [comment]
I just saw https://github.com/poldracklab/fmriprep/issues/1584#issuecomment-484137250

**Comment by effigies** [comment]
Should be fine as long as we don't do pre-installs. But perhaps `<0.5.0a0` is a better move.

**Comment by emdupre** [comment]
There's a brand new release that fixes this problem ! You could pin to `nilearn >= 0.5.2`

**Comment by effigies** [comment]
Not sure I want to commit to >=0.5.2. There are other issues in the 0.5 series that haven't been addressed and we may need to go with <0.5.0a in the end.

**Comment by oesteban** [comment]
Banning 0.5.0 and 0.5.1 seems just fine for now. Let's not trigger an update for all installed systems as fmriprep is indeed compatible with older versions.

**Pull request merged**
