### PR TITLE
FIX: Verify proc file exists before reading

### LINKED ISSUE #1453: Issue Running Latest Release Withing Singularity Image
Hello,

When I try to run the latest release (1.2.5) as a singularity container on a HPC system. I get the following errors:
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/cli/run.py", line 271, in main
    if 'docker' in Path('/proc/1/cgroup').read_text():
  File "/usr/local/miniconda/lib/python3.6/pathlib.py", line 1194, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/local/miniconda/lib/python3.6/pathlib.py", line 1181, in open
    opener=self._opener)
  File "/usr/local/miniconda/lib/python3.6/pathlib.py", line 1035, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/local/miniconda/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/proc/1/cgroup'

I attempted the various suggestions from: https://github.com/poldracklab/fmriprep/issues/780, without success.

Strangely, when I run fmriprep from the release corresponding to 09/10/2018 this container runs without issue.

Let me know if Ineed to provide anything else!

-Tim

### PR DESCRIPTION
**Pull request by effigies**
## Changes proposed in this pull request

Check that `/proc/1/cgroup` exists before attempting to read it.

Fixes #1453.

### CODE REVIEW

**Comment by tjhendrickson** [comment]
Has this change been pushed to docker hub? I cannot seem to build docker images directly from the github repository.

**Comment by effigies** [comment]
You should be able to use `poldracklab/fmriprep:unstable` to use the latest master. But we have not yet made a release that includes this PR.

**Comment by tjhendrickson** [comment]
Ugh, I ran into another error with poldracklab/fmriprep:unstable. Here it is: **No module named 'fmriprep.interfaces.images**. Any ideas?

**Comment by effigies** [comment]
Yeah, there's been a reorganization, and apparently we haven't caught all the vestiges of the old organization. Thanks for testing before we hit the release button... Could you share your command line?

**Comment by tjhendrickson** [comment]
Got it. 

Here is the snippet from an executable that runs fmriprep:

subj_id=A01
#ses_id=SESSIONID
data_dir=/home/umii/hendr522/scratch.global.data/BIDS/Ann_Van_de_Winckel_Stroke

singularity run -B ${data_dir}/BIDS_output:/bids_dir -B ${data_dir}/fmriprep_output_new:/output_dir  /home/umii/hendr522/singularity_images/poldracklab_fmriprep_unstable-2018-12-20-a7b8e494e
dad.simg /bids_dir /output_dir participant --participant_label ${subj_id} --fs-license-file /output_dir/license.txt --use-aroma --medial-surface-nan --nthreads 3 --mem_mb 90000 --longitudinal

**Comment by tjhendrickson** [comment]
I'm dealing with some time sensitive processing, is there a version that I could use that is guaranteed to be stable?

**Comment by effigies** [comment]
It looks like 1.2.2 is the last version that predates the `cgroup` check. We can try to get `master` to a state that works for you by tomorrow, if you have time for some back-and-forth, but I'm hesitant to push a new release just before the holidays.

**Comment by effigies** [comment]
Also, can you provide any more context for the `No module named 'fmriprep.interfaces.images'` error? Was there a traceback? I'm not able to find a place that attempts to use it.

**Pull request merged**
