### PR TITLE
Flake8 cleanup workflows/anatomical

### PR DESCRIPTION
**Pull request by effigies**
Mostly line length and block spacing issues. These keep popping up when I style check before committing in #347, but I don't really want to infect that PR with these cleanups.

If people don't like these changes, can we put in a tox.ini or something to tell flake8 what style issues to report?

### CODE REVIEW

**Comment by rwblair** [comment]
LGTM. Maybe we bump minimum line length? I know its against the holy scripture for public code... Pylint  only complains at 100 characters. But it also has some interesting ideas about what good looking code is that are not in pep8.

**Comment by oesteban** [comment]
I'm totally open to whatever standard you guys want to stick with. My only issue is that 79 characters is quite reduced, I would advocate for 99.

**Comment by effigies** [comment]
99 works. Added a `tox.ini`, and ran through the rest of the workflows directory to get a sense of how much changes.

Mostly finding some blank line counts and unused imports. A few undefined names, which I left alone, not knowing what they were supposed to be.

**Comment by oesteban** [comment]
Is this ready to merge?

**Comment by effigies** [comment]
Yup.



Sent on my Samsung Galaxy S® 5


-------- Original message --------

**Pull request merged**
