### PR TITLE
HMC refactor

### LINKED ISSUE #267: MCFLIRT is introducing slow frequency confound
image

https://fsl.fmrib.ox.ac.uk/fsl/fslwiki/MCFLIRT
> As part of the initial 8mm search, an identity transformation is assumed between the middle volume and the adjacent volume. The transformation found in this first search is then used as the estimate for the transformation between the middle volume and the volume beyond the adjacent one. This scheme should lead to much faster optimization and greater accuracy for the majority of studies where subject motion is minimal. In the pathalogical cases, this scheme does not penalise the quality of the final correction. 
> 
> If mean registration is used, the curent motion correction parameters are applied to the time-series, the volumes are averaged to create a new template image and the same 3-stage correction is carried out using this new mean image as a template.

### PR DESCRIPTION
**Pull request by chrisfilo**
- Closes #267 by performing interpolation using ANTs
- Outputs EPI in T1w space instead of the EPI space
- Use float32 when applying transforms (turns out they were calculated using float32 anyway)

### CODE REVIEW

**Comment by chrisfilo** [comment]
I'm waiting for @rwblair to run it through the paces and confirm that it indeed fixes #267.

**Comment by rwblair** [comment]
On ds054 style datasets we error out with the following:
```
Module ConfoundDiscoverer has no input called inputnode.t1_transform
Module ConfoundDiscoverer has no input called inputnode.reference_image
```
Those two inputs are referenced in base.py, and are not defined in confounds.py

**Comment by chrisfilo** [comment]
Yeah - the refactor, breaks ds054 (that's why the tests were
commented out). We agreed with @oesteban to not try to adapt the ds054 and
leave it to his fieldmap branch.

Did you check that this PR indeed removes the trend in DVARS?

**Comment by rwblair** [comment]
Its currently being rerun on sub-313 from the beast dataset, will review its output in the morning.

**Pull request merged**
