### PR TITLE
Update CHANGES.rst

### PR DESCRIPTION
**Pull request by effigies**
Thinking we should go ahead and release niworkflows 0.0.8/0.1.0 and fmriprep 0.4.5. Any objections?

### CODE REVIEW

**Comment by chrisfilo** [comment]
Let me do pybids as well.

**Comment by chrisfilo** [comment]
pybids 0.2.0 is out - give it a moment to build
https://github.com/INCF/pybids/releases/tag/0.2.0

**Comment by effigies** [comment]
Updated the pybids pin. Will wait on poldracklab/niworkflows#175 approval to go forward with releasing fmriprep 0.4.5, but this can go in now or wait on that. Your call.

**Comment by effigies** [comment]
The 4G RAM limit on Circle seems to be being hit more regularly. 😕

**Pull request merged**
