### PR TITLE
[FIX] Corrects Dockerfile WORKDIR.

### PR DESCRIPTION
**Pull request by pvelasco**
## Changes proposed in this pull request

It sets the last WORKDIR in the docker image to /tmp, instead of /root/src/fmriprep, so now you can run the docker container as a user different from root.  

As far as I can tell, if no working directory is specified by the `-w` parameter, fmriprep will try to create the folder `work` under `/root/src/fmriprep`, and only root has access to that folder.

This should fix problems people have found when running docker specifying a user (e.g., ref #1060).

**Please review and check the following**:

  - [x] I have read the [guidelines for contributions](https://github.com/poldracklab/fmriprep/blob/master/CONTRIBUTING.md).
  - [x] I understand that my contributions will not be merged unless the work is
        finished (i.e. no ``[WIP]`` tag remains in the title of my PR) and tests pass.
  - [x] The proposed code follows the
        [coding style](https://github.com/poldracklab/fmriprep/blob/master/CONTRIBUTING.md#fmriprep-coding-style-guide),
        to the extent I understood them (and I will address any comments raised by the PR's reviewers in this regard).
  - [x] \(Optional\) I opt-out from being listed in the `.zenodo.json` file.

### CODE REVIEW

**Comment by oesteban** [comment]
Hi @pvelasco, would this #1204 fix your issue? Any particular reason to use `/tmp` instead of `/scratch` ?

**Comment by effigies** [comment]
@oesteban I understand the problem here to be that permissions issues when running Docker with the `-u <UID>` flag. You should make sure that `/scratch` is world-writable, so working directories can be written within the container. Perhaps we should go ahead and run one of our tests with the `-u` flag.

**Comment by pvelasco** [comment]
@oesteban, I tried using `/scratch`, but it doesn't work because it is created by root and any other users don't have writing privileges; you would have to `chmod` in the Dockerfile.
Why not using `/tmp`?  That's precisely its purpose: temporary scratch space readable/writable by everybody.

**Comment by oesteban** [comment]
@pvelasco, you are right. I was overthinking this.

@effigies I am testing that on a different branch. Will send PR when working.

**Pull request merged**
