### PR TITLE
[RTM] singularity related workaround

### PR DESCRIPTION
**Pull request by chrisfilo**
See https://github.com/singularityware/singularity/issues/571#issuecomment-320826366

### CODE REVIEW

**Comment by chrisfilo** [comment]
This does not solve the issue:

```
[chrisgor@sh-101-58 /tmp]$  singularity pull --name "meatballs.img" docker://filo/fmripreptest
Initializing Singularity image subsystem
Opening image file: meatballs.img
Creating 21553MiB image
Binding image to loop
Creating file system within image
Image is done: meatballs.img
Docker image path: index.docker.io/filo/fmripreptest:latest
Cache folder set to /tmp/docker
[20/28] |=========================|---------|  71.4%

[28/28] |===================================| 100.0%
Importing: base Singularity environment
Importing: /tmp/docker/sha256:b3e1c725a85f0953e81815b7c7aabfad9ebfd90af53f99248981282b8045d787.tar.gz
Importing: /tmp/docker/sha256:4daad8bdde31f5969d6a44800e993a911bed25853b2f89417b07ce7f0ac67714.tar.gz
Importing: /tmp/docker/sha256:63fe8c0068a811103c702452985368fc99014f83b5f0151cf631644f13f383b2.tar.gz
Importing: /tmp/docker/sha256:4a70713c436f2350e8a9f1c1e6c823290f331254c6c21d5657056499d8575608.tar.gz
Importing: /tmp/docker/sha256:bd842a2105a862f62ba4ad726531029be49046c290307e9c07a688c89f4606e6.tar.gz
Importing: /tmp/docker/sha256:fdac77affe64c1a630b123ef6ead94ed5d6c141c010b95447d4dee02f1963110.tar.gz
Importing: /tmp/docker/sha256:3e57ade618cafc2165ed0a14df5e5cfd5487c48a957c48e2c9956cc362a58697.tar.gz
Importing: /tmp/docker/sha256:6efcf3dec9b46793d2db07fea051ea8e191cb6167e47172d6e5741dda0ab72c8.tar.gz
Importing: /tmp/docker/sha256:f359ec987f7f94af8c25d97a3a8c5bc75734c0aeedd377ceb0cb8b14e9abaf35.tar.gz
Importing: /tmp/docker/sha256:19bc41c21195364b4e1ce369dc375f1a1892f8ad2a5aa876f7c5630f468636ef.tar.gz
Importing: /tmp/docker/sha256:45faccff3f87f41937538d9f0b2aec5d5900d6511c9d63d8879cb5365bf76633.tar.gz
Importing: /tmp/docker/sha256:3be9305df660394632098c6fd9aaba82b59466d3ff0f5fe10717f744838c253c.tar.gz
Importing: /tmp/docker/sha256:d8a773ba4cc809b976bf56649e2548498c557658e06ee030dd67580e65d5c267.tar.gz
Importing: /tmp/docker/sha256:e3e4d2db349271ffb62e4b2b54e1d58b97fa26295ac4a35f04d55997710a46ca.tar.gz
Importing: /tmp/docker/sha256:9e39963ed8c81b0a79f73d8148e6321033ecd035a1efed055e314d514ba1e42c.tar.gz
Importing: /tmp/docker/sha256:e005d35430e0796cc920c3a86776cedb1d27e2ffda5b6cd3cfea6638947028fe.tar.gz
Importing: /tmp/docker/sha256:7576ecf0c975e7f6cf4065c7bcc243f4b60983d55c2f0fc6bea984960425f47c.tar.gz
Importing: /tmp/docker/sha256:e0b949de7c6430e54cab63f4cd26cb923e67e765b46431c5d862aa44164c2bc1.tar.gz
Importing: /tmp/docker/sha256:fc2cc9a246854a2954f06ec8e32e3e78e0eee27a5557f838327d48ef8edf5be0.tar.gz
Importing: /tmp/docker/sha256:4679d2793d671b6ce3ae7b643af9a4268dff83631f4e4ada7e6027fc0878e9d9.tar.gz
Importing: /tmp/docker/sha256:1db248c81c48bed03af0efd07853bbb7b5b0d31a0b02645d101cb60499f78f6f.tar.gz
Importing: /tmp/docker/sha256:21e6eb23b10b172c6f9bda4f5eb9b98dcbcf5da28767e967f72c83741f92bfd2.tar.gz
Importing: /tmp/docker/sha256:d3cb0c1206e30dde6a0358a44db15800e4c6a84d879100ae14d91fdba4e1a9e0.tar.gz
Importing: /tmp/docker/sha256:1ba5605f9efa250ca43059ca244eac51d859e6fcffb7d7d89da3427f8e0f3047.tar.gz
Importing: /tmp/docker/sha256:ffc5ced56eadd564f742f2ee62c3476914c9f90b36557e74a97c3b7297404341.tar.gz
Importing: /tmp/docker/sha256:d63f3884ec05c133e14d4d7934c8c3c72c1365db3e9cc93ab321a60d8d7dab2c.tar.gz
Importing: /tmp/docker/sha256:72658d781de5b0a3992bd09686a02ab5decc46580187eeaf5641973f55c52642.tar.gz
Importing: /tmp/docker/sha256:1c2c9ec61ddfaca4cb602982b98bbb5f91cff765838090a35018e2341a9aa18b.tar.gz
Importing: /tmp/metadata/sha256:11ab01a97be84bff3ff21bcc31d6c77a588d1f58bf67ae804439dab3b30de816.tar.gz
Done. Container is at: meatballs.img
[chrisgor@sh-101-58 /tmp]$
[chrisgor@sh-101-58 /tmp]$
[chrisgor@sh-101-58 /tmp]$ singularity run meatballs.img
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 6, in <module>
    from pkg_resources import load_entry_point
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2985, in <module>
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2971, in _call_aside
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2998, in _initialize_master_working_set
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 651, in _build_master
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 644, in __init__
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 700, in add_entry
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1990, in find_on_path
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2399, in from_location
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2740, in _reload_version
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2364, in _version_from_file
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2532, in _get_metadata
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1873, in get_metadata_lines
  File "/usr/local/miniconda/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1861, in get_metadata
PermissionError: [Errno 13] Permission denied: '/usr/local/miniconda/lib/python3.6/site-packages/.wh.conda-4.3.11-py3.6.egg-info'
```

**Comment by chrisfilo** [comment]
This workaround does work.

**Comment by oesteban** [comment]
I think this is a problem of filesystem synchronization and conda. This:

```Dockerfile
RUN conda install -y mkl=2017.0.1 mkl-service;  sync &&\
    conda install -y numpy=1.12.0 \
                     scipy=0.18.1 \
                     scikit-learn=0.18.1 \
                     matplotlib=2.0.0 \
                     pandas=0.19.2 \
                     libxml2=2.9.4 \
                     libxslt=1.1.29\
                     traits=4.6.0; sync &&  \
    chmod +x /usr/local/miniconda/bin/*; sync && \
    conda clean --all -y; sync && \
    conda clean -tipsy && sync
```

worked for me (without the workaround deleting files).
Actually, the `chmod` line can be removed if those `sync` are included (that is a workaround to a problem related to the lack of `sync`s).

My output with that docker file:
```Bash
[oesteban@sh-101-58 /tmp]$ singularity pull --name "meatballs.img" docker://oesteban/fmripreptest
...
Done. Container is at: meatballs.img
[oesteban@sh-101-58 /tmp]$ singularity run meatballs.img
usage: fmriprep [-h] [-v]
                [--participant_label PARTICIPANT_LABEL [PARTICIPANT_LABEL ...]]
                [-t TASK_ID] [--debug] [--nthreads NTHREADS]
                [--omp-nthreads OMP_NTHREADS] [--mem_mb MEM_MB]
                [--use-plugin USE_PLUGIN] [--anat-only]
                [--ignore-aroma-denoising-errors]
                [--ignore {fieldmaps,slicetiming} [{fieldmaps,slicetiming} ...]]
                [--longitudinal] [--bold2t1w-dof {6,9,12}]
                [--output-space {T1w,template,fsnative,fsaverage,fsaverage6,fsaverage5} [{T1w,template,fsnative,fsaverage,fsaverage6,fsaverage5} ...]]
                [--template {MNI152NLin2009cAsym}]
                [--output-grid-reference OUTPUT_GRID_REFERENCE] [--use-aroma]
                [--skull-strip-ants] [--no-skull-strip-ants] [--fmap-bspline]
                [--fmap-no-demean] [--use-syn-sdc] [--force-syn]
                [--no-freesurfer] [--no-submm-recon] [-w WORK_DIR]
                [--reports-only] [--write-graph]
                bids_dir output_dir {participant}
fmriprep: error: the following arguments are required: bids_dir, output_dir, analysis_level
```

**Comment by chrisfilo** [comment]
Good investigative work. Do you want to open a new pull request?

**Comment by oesteban** [comment]
Whatever is more convenient to you. I don't really mind either way.

**Comment by satra** [comment]
@kaczmarj - could you please update neurodocker with this info ?

**Pull request closed without merging**
