### PR TITLE
 [ENH] Adopt versioneer to compose version names

### PR DESCRIPTION
**Pull request by oesteban**
This not only makes more detailed the version that is used in development (particularly when using containers), it also simplifies several steps of our release workflow (no need to manually handle versions anymore).

The system has been tested on mriqc for a while now, and it is simple:

- In dev environments (`pip install -e`): versioneer parses the version and gives you the version string:
  ```
  fmriprep --version
  fmriprep v1.0.8+3.gea418f9
  ```
  A new `get_version.py` file under the root directory reads the version without having fmriprep installed:
  ```
  python get_version.py 
  1.0.8+3.gea418f9
  ```
  When my system is 3 commits after tag 1.0.8, HEAD pointing to `ea418f9`. For some reason, there is always a `g` before the commit. Haven't looked into versioneer to know why is that.

- When deployed, a `VERSION` file is written under the `fmriprep/` folder. If the file is found, that is the version reported. This file is generated before building the docker image or uploading to Pypi with the appropriate tag if releasing.

### CODE REVIEW

**Comment by oesteban** [comment]
Okay, this is working for CircleCI. Now it is possible to know the exact version of FMRIPREP people are using - https://1310-53608443-gh.circle-artifacts.com/0/tmp/ds005/derivatives/fmriprep/sub-01.html says

```
FMRIPREP version: 1.0.8+10.gdfd8dae4
```

Which is the latest commit I submitted.

**Comment by effigies** [comment]
Seems fine to me. I assume that the two new big files are basically boilerplate?

If it builds, I'm okay with it.

**Comment by oesteban** [comment]
Yes, just in case versioneer is not installed

**Comment by effigies** [comment]
Looks like this is breaking RTD. Can look into it if you don't have time.

**Comment by oesteban** [comment]
I can check

**Comment by oesteban** [comment]
Back on track

**Pull request merged**
