### PR TITLE
[FIX] Fix AddTPMs interface to write results in proper path

### PR DESCRIPTION
**Pull request by oesteban**
Additionally, make sure that the output image is float. This PR addresses the following error:

```
Node: fmriprep_wf.single_subject_13_wf.func_preproc_task_fb_run_04_wf.bold_confounds_wf.acc_roi
Working directory: /scratch/users/oesteban/fmriprep-phase2/work/ds000212/fmriprep_wf/single_subject_13_wf/func_preproc_task_fb_run_04_wf/bold_confounds_wf/acc_roi

Node inputs:

erode_mm = <undefined>
erode_prop = 0.6
ignore_exception = False
in_mask = /scratch/users/oesteban/fmriprep-phase2/work/ds000212/fmriprep_wf/single_subject_13_wf/anat_preproc_wf/skullstrip_ants_wf/t1_skull_strip/highres001_BrainExtractionMask.nii.gz
in_tpm = /scratch/users/oesteban/fmriprep-phase2/work/ds000212/fmriprep_wf/single_subject_13_wf/anat_preproc_wf/t1_seg/highres001_BrainExtractionBrain_prob_0_tpmsum.nii.gz
mask_erode_mm = <undefined>
mask_erode_prop = 0.21599999999999997
prob_thresh = 0.95

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 52, in run_node
    result['result'] = node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 405, in run
    self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 508, in _run_interface
    self._result = self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 640, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base.py", line 1089, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/utils.py", line 81, in _run_interface
    self.inputs.prob_thresh
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/utils.py", line 235, in _tpm2roi
    tpm_img = nb.load(in_tpm)
  File "/usr/local/miniconda/lib/python3.6/site-packages/nibabel/loadsave.py", line 49, in load
    filename)
nibabel.filebasedimages.ImageFileError: Cannot work out file type of "/scratch/users/oesteban/fmriprep-phase2/work/ds000212/fmriprep_wf/single_subject_13_wf/anat_preproc_wf/t1_seg/highres001_BrainExtractionBrain_prob_0_tpmsum.nii.gz"
```

### CODE REVIEW

**Comment by oesteban** [comment]
This patch seems to fix for the issue.

**Comment by effigies** [comment]
Looks okay, but I don't see how this is related to the error you posted. `Cannot work out the file type` almost always means a corrupted header, often in the form of an uncompressed file that was saved with a `.gz` extension.

**Comment by oesteban** [comment]
The outputs of this interface were stored in the working directory of a different node. I am pretty sure that a race condition happened and the file was corrupted by fmriprep execution itself. WDYT?

**Comment by effigies** [comment]
Ah, yeah, that seems plausible. I skipped over the "path" part of the title and focused on the data type part of the description.

**Pull request merged**
