### PR TITLE
PIN: nipreps/niworkflows#485

### PR DESCRIPTION
**Pull request by effigies**
Merged nipreps/master into nipreps/niworkflows#485 and pushed to my own remote. Opening PR to check that we get sensible brain masks on CI.

cc @oesteban If this passes, I'll merge the niworkflows PR.

### CODE REVIEW

**Comment by oesteban** [comment]
Thanks much!

**Comment by effigies** [comment]
@oesteban could you look at these errors? They seem to be templateflow-related:

```
Process Process-2:
 
Traceback (most recent call last):
 
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
 
    self.run()
 
  File "/usr/local/miniconda/lib/python3.7/multiprocessing/process.py", line 99, in run
 
    self._target(*self._args, **self._kwargs)
 
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/workflow.py", line 80, in build_workflow
 
    retval['workflow'] = init_fmriprep_wf()
 
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 64, in init_fmriprep_wf
 
    single_subject_wf = init_single_subject_wf(subject_id)
 
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/base.py", line 287, in init_single_subject_wf
 
    func_preproc_wf = init_func_preproc_wf(bold_file)
 
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/workflows/bold/base.py", line 306, in init_func_preproc_wf
 
    bold_reference_wf = init_bold_reference_wf(omp_nthreads=omp_nthreads)
 
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/func/util.py", line 117, in init_bold_reference_wf
 
    omp_nthreads=omp_nthreads, pre_mask=pre_mask)
 
  File "/usr/local/miniconda/lib/python3.7/site-packages/niworkflows/func/util.py", line 325, in init_enhance_and_skullstrip_bold_wf
 
    'MNI152NLin2009cAsym', resolution=1, label='brain', suffix='probseg'))),
 
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/ants/base.py", line 75, in __init__
 
    super(ANTSCommand, self).__init__(**inputs)
 
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 673, in __init__
 
    super(CommandLine, self).__init__(**inputs)
 
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/core.py", line 183, in __init__
 
    self.inputs = self.input_spec(**inputs)
 
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/specs.py", line 66, in __init__
 
    super(BaseTraitedSpec, self).__init__(**kwargs)
 
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 329, in validate
 
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
 
  File "/usr/local/miniconda/lib/python3.7/site-packages/nipype/interfaces/base/traits_extension.py", line 134, in validate
 
    self.error(objekt, name, str(value))
 
  File "/usr/local/miniconda/lib/python3.7/site-packages/traits/trait_handlers.py", line 172, in error
 
    value )
 
traits.trait_errors.TraitError: The 'input_image' trait of an ApplyTransformsInputSpec instance must be a pathlike object or string representing an existing file, but a value of '[]' <class 'str'> was specified.
 ```

**Comment by oesteban** [comment]
At `docker build`, the step where we install fMRIPrep:
```
ERROR: niworkflows 0.9.0+639.g3a71c56 has requirement templateflow>=0.6.0rc1, but you'll have templateflow 0.5.2 which is incompatible.
 
ERROR: sdcflows 1.2.3 has requirement niworkflows<1.4,>=1.2.0rc4, but you'll have niworkflows 0.9.0+639.g3a71c56 which is incompatible.
```

**Comment by oesteban** [comment]
All-green now. Haven't checked on the reports yet though

**Comment by oesteban** [comment]
Okay, there's something odd about the xforms of ds210 and the AROMA results of the second run of ds005 are also a bit funny. I'll have to revise what's going on here.

**Comment by mgxd** [comment]
this is super close, anything I can do to push this in?

**Comment by oesteban** [comment]
This is mostly on my plate. I've been focusing on nipreps/niworkflows#507 because these two were too big to handle in parallel and it felt I was unlocking more work with the other PR. When I get a sense of why this is not working, I may need to ping you back 👍

**Comment by oesteban** [comment]
Waiting on #2114

**Comment by effigies** [comment]
@oesteban Definitely getting some skull in ds210: https://13684-53175327-gh.circle-artifacts.com/0/tmp/ds210/derivatives/fmriprep/sub-02.html#datatype-figures_desc-summary_echo-1_run-1_suffix-bold_task-cuedSGT

Significant regression from `master`: https://13677-53175327-gh.circle-artifacts.com/0/tmp/ds210/derivatives/fmriprep/sub-02.html#datatype-figures_desc-summary_echo-1_run-1_suffix-bold_task-cuedSGT

**Comment by oesteban** [comment]
Yup, I'm not super-happy with the results. The 0.5 threshold might be too generous, and I'm not positive trial and error is the right approach to optimize it.

**Comment by oesteban** [comment]
Okay, it seems the problems of ds210 are gone with 20.1.0 as base. Now, though, I think this would benefit a lot from finishing nipreps/niworkflows#408 because the INU correction is not liking the composite echo input.

The funny (empty) component of ds005 is still there though.

**Comment by oesteban** [comment]
I've been working on updating https://github.com/nipreps/niworkflows/pull/408, and reached to the conclusion that it won't affect this particular change, as we are always using the first echo for masking purposes.

In diagnosing what's going on with the ROIs plot of ds210, I found #2162.

I'll play a bit with the threshold, which after all is the only knob we can actually tune. Because of how I generated the probabilistic mask, there's no real meaning for values in the mask (i.e., those are not a model fitting result or anything, just mathematical morphology and smoothing operations to have the edges be smoother). Therefore, using a threshold other than 0.5 is as valid (or invalid) as 0.5 itself.

**Comment by oesteban** [comment]
Okay, I think this is ready.

- Figured out that the weird component of AROMA is actually a mild bug when calculating the color scale of the components (or a component with very low loadings compared to the others).
- It seems that 0.85 is a good threshold for the brain mask (gives you something pretty close to that we used to have). The value is quite arbitrary, but it is also true that this mask is not really probabilistic, just has some smoothing around the edges.

**Comment by oesteban** [comment]
(made it a draft until the niworkflows PR is merged)

**Comment by oesteban** [comment]
Because the default threshold is now 0.85 in the workflow definition itself, this PR is no longer needed (results of integration will come with the build associated with https://github.com/poldracklab/fmriprep/commit/11683c7a3f6eeb899709bf4173238f351ee18eef)

**Pull request closed without merging**
