### PR TITLE
[FIX] Missing report output - #1339

### LINKED ISSUE #1339: Missing report output
Hi!

I'm new to fmriprep and have been playing around with a stripped down version of a dataset: one participant, one functional multiband BOLD series + sbref, T1w+T2w anatomicals, two spin echo epi scans with opposite phase encoding for inhomogeneity corrections; all BIDS-validated.

I'm on OSX with Docker 18.06.1 and from the terminal output everything seems to run smoothly (some warnings, but no errors or crashes). However the final html-report is never populated with more than the Summary+Anatomical (i.e. the Functional section is missing). Moreover, the func reportlets don't get produced, nor does the func folder and its content in the output directory.

I mentioned some warnings, they typically look like this (the "No contour levels were found" message being repeated over and over): 
```
 [Node] Setting-up "fmriprep_wf.single_subject_ACON1PILOT5P4_wf.func_preproc_ses_fmapse_task_loc_acq_ACon104_run_01_wf.bold_confounds_wf.rois_plot" in "/scratch/fmriprep_wf/single_subject_ACON1PILOT5P4_wf/func_preproc_ses_fmapse_task_loc_acq_ACon104_run_01_wf/bold_confounds_wf/rois_plot".
181022-14:53:15,888 nipype.workflow INFO:
	 [Node] Running "rois_plot" ("niworkflows.interfaces.masks.ROIsPlot")
/usr/local/miniconda/lib/python3.6/site-packages/matplotlib/contour.py:1173: UserWarning: No contour levels were found within the data range.
  warnings.warn("No contour levels were found"
```

```
 [Node] Running "bold_rpt" ("niworkflows.interfaces.registration.SimpleBeforeAfterRPT")
181022-14:52:20,227 nipype.workflow INFO:
	 [Node] Finished "fmriprep_wf.single_subject_ACON1PILOT5P4_wf.func_preproc_ses_fmapse_task_loc_acq_ACon104_run_01_wf.bold_bold_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.skullstrip_second_pass".
/usr/local/miniconda/lib/python3.6/site-packages/matplotlib/contour.py:1173: UserWarning: No contour levels were found within the data range.
  warnings.warn("No contour levels were found"
```

```
[Node] Finished "fmriprep_wf.single_subject_ACON1PILOT5P4_wf.func_preproc_ses_fmapse_task_loc_acq_ACon104_run_01_wf.bold_bold_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.combine_masks".
/usr/local/miniconda/lib/python3.6/site-packages/matplotlib/contour.py:1173: UserWarning: No contour levels were found within the data range.
  warnings.warn("No contour levels were found"
```

Here's an example of a command line I've been running (I've tried several with the same result):

```
docker run -it --rm \
-v /Users/markushs/Documents/testing_fmriprep/data_bids:/data:delegated \
-v /Users/markushs/Documents/testing_fmriprep/out:/out:delegated \
-v /Users/markushs/Documents/testing_fmriprep/work:/scratch:delegated \
-v /Users/markushs/Documents/testing_fmriprep/license.txt:/opt/freesurfer/license.txt \
poldracklab/fmriprep:latest /data /out participant \
-w /scratch \
--output-space T1w \
--ignore slicetiming \
--fs-no-reconall \
--nthreads 3 \
--stop-on-first-crash
```

(specifying mounts as delegated after seeing #1012, however same problem without :delegated)

Any ideas why the reports are missing? May be related to #1313, however I don't get any errors. 

Thanks!
Markus

### PR DESCRIPTION
**Pull request by kasbohm**
Fixes #1339 
The previous version failed on edge cases where 'anat', 'fmap', 'func', 'dwi' strings were found in the file path, for example, if a session was named ses-noanatomicals. Output files were then placed wrongly.

## Changes proposed in this pull request
Proposed small change to how _mod_ is set  (to the name of parent folder of _self.inputs.source_file_). This requires valid BIDS structure, but I assume that can be assumed. 

Are there cases where _self.inputs.source_file_ can be something other than 'anat', 'fmap', 'func', 'dwi' so we need to create exceptions/tests for that?

### CODE REVIEW

**Comment by effigies** [comment]
Thanks for this! I *think* it should be okay, but I'll try to have a more critical look at some point today.

**Comment by oesteban** [comment]
Hi @kasbohm, thanks a lot for this contribution. I've just submitted a PR to your branch adding a doctest for the test-case you are fixing. It will also synchronize with master (so we should not see the red cross for ds005 anymore).

Please also confirm if you want to add your name to the .zenodo.json file.

Thanks very much!

**Comment by kasbohm** [comment]
Hi @effigies and @oesteban! Thanks, do I just merge the PR on my fork, and would this step have been avoided if I had performed a `git merge upstream/master` before committing? Please add me to the .zenodo.json if that is appropriate.

Cheers!

**Comment by oesteban** [comment]
The test passed, merging in.

**Pull request merged**
