### PR TITLE
[ENH] Template-based masking of EPI boldrefs

### PR DESCRIPTION
**Pull request by oesteban**
## Changes proposed in this pull request
This PR explores template-based masking of boldrefs to initialize the skull-stripping workflow (see issues related on #1000).

This PR is also highly related to #1050.

## Documentation that should be reviewed

This is WIP, will update documentation when it is proven to work out.

### CODE REVIEW

**Comment by oesteban** [comment]
So this are the results:

* https://2488-53608443-gh.circle-artifacts.com/0/tmp/data/reports/ds000116/sub-12_task-visualoddballwithbuttonresponsetotargetstimuli_run-02_bold_masks.svg
* https://2488-53608443-gh.circle-artifacts.com/0/tmp/data/reports/ds000133/sub-06_ses-post_task-rest_run-01_bold_masks.svg
* https://2488-53608443-gh.circle-artifacts.com/0/tmp/data/reports/ds000140/sub-32_task-heatpainwithregulationandratings_run-02_bold_masks.svg
* https://2488-53608443-gh.circle-artifacts.com/0/tmp/data/reports/ds000157/sub-23_task-passiveimageviewing_bold_masks.svg
* https://2488-53608443-gh.circle-artifacts.com/0/tmp/data/reports/ds000210/sub-06_task-rest_run-01_echo-1_bold_masks.svg
* https://2488-53608443-gh.circle-artifacts.com/0/tmp/data/reports/ds000210/sub-06_task-rest_run-01_echo-2_bold_masks.svg
* https://2488-53608443-gh.circle-artifacts.com/0/tmp/data/reports/ds000210/sub-06_task-rest_run-01_echo-3_bold_masks.svg
* https://2488-53608443-gh.circle-artifacts.com/0/tmp/data/reports/ds000216/sub-03_task-rest_echo-2_bold_masks.svg
* https://2488-53608443-gh.circle-artifacts.com/0/tmp/data/reports/ds000216/sub-03_task-rest_echo-3_bold_masks.svg
* https://2488-53608443-gh.circle-artifacts.com/0/tmp/data/reports/ds000216/sub-03_task-rest_echo-4_bold_masks.svg
* https://2488-53608443-gh.circle-artifacts.com/0/tmp/data/reports/ds000237/sub-03_task-MemorySpan_acq-multiband_run-01_bold_masks.svg
* https://2488-53608443-gh.circle-artifacts.com/0/tmp/data/reports/ds000237/sub-06_task-MemorySpan_acq-multiband_run-01_bold_masks.svg

I still need to investigate what happened here: https://2488-53608443-gh.circle-artifacts.com/0/tmp/data/reports/ds000216/sub-03_task-rest_echo-1_bold_masks.svg

**Comment by oesteban** [comment]
The problem with echo 1 of ds216 seems to have been introduced here https://5172-53175327-gh.circle-artifacts.com/0/tmp/data/reports/ds000216/sub-03_task-rest_echo-1_bold_masks.svg

**Comment by oesteban** [comment]
Seems like the weird problem on ds216 is now fixed. At this point I would ask: do you think it is maybe worth changing the whole algorithm to the following?:

1. Initialization: ANTs' AI, using the template as target and the boldref as moving
2. Gross mask, applyTransform on the inverted transform of 1)
3. N4 on the boldref with the gross mask
4. First registration: very fast refinement (Rigid) of the gross mask using the template as target and the boldref as moving and initialized with 1)
5. N4 on the boldref with the less-gross mask
6. Second registration (Affine) initialized with 4)
7. Remaining boldref refinement with the final mask

**Comment by effigies** [comment]
Let's test on the subject from #1181, as well.

**Comment by oesteban** [comment]
Artifacts in the latest commit without `[skip ci]` -> https://circleci.com/gh/oesteban/fmriprep/2525#artifacts/containers/0

**Comment by oesteban** [comment]
Thanks a lot for your precious feedback! @ZhifangYe

> 1. The pre_mask's header should be fixed before N4 correction. I encountered Inputs do not occupy the same physical space! error on one of my test image.

Could you provide more information about the error (full trace) or even the dataset (privately is fine) where this is happening? This is a new caching procedure we are testing and it does not surprise me you got this kind of problem.

> 2. The N4 correction has no effect on some of the unwrapped images (eg. sub-26 rest) in bold_bold_trans_wf. I tried to run N4 correction manually on the ref_image_valid.nii.gz and it yielded the same incorrect result.

Cool, sub-26_task-rest is now within the regression tests, so I'll work on this one particularly.

> 3. What if the BOLD image only covers part of brain volume? I think the initial affine transformation would generate a quite large mask for N4 correction. I think we should include some partial volume scan (especially for scans only covers 30-40 slices parallels to the long axis of hippocampus) in the test battery to see how well the method works.

This question is also very pertinent. I'll dig up some partial FoV datasets from OpenNeuro and add them to the test battery.

Thanks a lot for your input, very much appreciated!

**Comment by oesteban** [comment]
Fixes #1000 
Fixes #1181

**Comment by oesteban** [comment]
Ref #900

**Comment by ZhifangYe** [comment]
Here's the fMRIprep error log and the verbose log of N4 correction command.
image
image

I think it's due to the very small discrepancy between the qform matrix of pre_mask and ref_image.

The following link is the raw data to replicate this error. https://www.dropbox.com/s/akfyadrih5lgcbd/sub-30.zip?dl=0

**Comment by oesteban** [comment]
> I think it's due to the very small discrepancy between the qform matrix of pre_mask and ref_image

Correct, there is a minimal difference in the qform.

**Comment by oesteban** [comment]
Alright, this ready for review (@ZhifangYe, @effigies). I've just fixed the issue of mismatched headers before N4. 

Since we don't make any promises about very limited FoV (https://github.com/poldracklab/fmriprep/labels/partial%20FOV), I propose to merge this in and come back later to the FoV issue.

Regarding sub-26_task-rest, please check out the regression tests under the test_pytest build of Circle.

**Comment by oesteban** [comment]
This is sub-26_task-rest: https://2591-53608443-gh.circle-artifacts.com/0/tmp/data/reports/ds001240/sub-26_task-rest_bold_masks.svg which looks okay.

We are seeing ds005 fail due to a problem checking filenames that is also happening in master. I'm guessing that would be a trivial change to do in master.

Thumbs up?

**Comment by oesteban** [comment]
ds005 problems addressed here - #1344 

If there are no further comments or voices against, I'll be merging later today and close #1050 as this PR supersedes that one.

Thanks to @ZhifangYe, this PR has been only possible with all the new data we have now for regression tests.

**Pull request merged**
