### PR TITLE
[ENH] Use float=True in ANTs registration

### PR DESCRIPTION
**Pull request by oesteban**
... and keep up with the changes in niworkflows

### CODE REVIEW

**Comment by effigies** [comment]
Pretty sure this will fail at the moment because of nipy/nipype#2105. Cherry pick 65193eafee05ded8e7d2def2c837a7449fb04bae

**Comment by oesteban** [comment]
I fetched upstream (poldracklab/fmriprep) and:
```
git cherry-pick 65193eafee05ded8e7d2def2c837a7449fb04bae
fatal: bad object 65193eafee05ded8e7d2def2c837a7449fb04bae
```

Am I missing something?

**Comment by effigies** [comment]
You might need to fetch my repo.

**Comment by oesteban** [comment]
We now have Travis?

**Comment by effigies** [comment]
Yeah, it's just to run style checks. #570

**Pull request merged**
