### PR TITLE
RF: Split reports/derivatives from anatomical workflow

### PR DESCRIPTION
**Pull request by effigies**
This is the work discussed in #456. Looking at it, it's actually kind of large, so I want to make it a separate PR before starting in on the functional workflows.

I also updated some names. The overall pattern I took was `<space>_<desc>`, which seemed roughly how things were being done. So `arw` (which I think meant anatomical reoriented... w) is now `t1_conform`, since it's essentially a conformation step. `bmask_mni` is `mni_mask`, to mirror `t1_mask`.

I think for the functional workflows, it makes sense to do a derivatives and reports node at the just-under-top level again, even though it's a bigger workflow overall. That will help keep the internal sub-workflows more modular and focused on processing than book-keeping.

### CODE REVIEW

**Comment by effigies** [comment]
Hierarchical workflow graph following a successful run (ds000114/sub-01/ses-01):
refactored_workflow

**Comment by effigies** [comment]
@chrisfilo What tests or further updates do you want to see before this goes in?

A few things I'm thinking of:

* [ ] Rethink a couple names in `surface_recon_wf`
  * [ ] `injector -> skull_strip_extern` or similar
  * [ ] `gifticonv -> fs_2_gii` or similar
* [ ] (Maybe) push all derivatives into `outputnode` first, and from there to `anat_derivatives_wf`

(I'll work on `func_preproc_wf` separately, just to keep the diffs more manageable.)

**Comment by chrisfilo** [comment]
This already look like a nice improvement in readability - I cannot think of anything in this workflow that desperately needs renaming.

**Comment by effigies** [comment]
Docs: https://326-78558509-gh.circle-artifacts.com/0/home/ubuntu/docs/workflows.html

**Pull request merged**
