### PR TITLE
MAINT: Better package data handling

### PR DESCRIPTION
**Pull request by oesteban**
Follows up on https://github.com/poldracklab/fmriprep/pull/1886#discussion_r352868543

### CODE REVIEW

**Comment by effigies** [comment]
Hmm. I would have gone the other way, and left MANIFEST.in as it is. It will be included in sdists, no matter what.

**Comment by oesteban** [comment]
Okay, IMHO we should go with the most widespread option for installation (`MANIFEST.in`) until it gets deprecated. That will ensure data of the package are installed in all scenarios. WDYT?

**Comment by effigies** [comment]
sdists themselves are not really recommended any longer (I can try to dig up a citation, but I just remember reading this somewhere). I don't think we need to go out of our way to prefer `MANIFEST.in` over `package_data`, and I would personally prefer to move away from it except as a way of including data that's in the root, needed only for building an sdist.

Here's the current situation:

```
$ python setup.py sdist | grep data
creating fmriprep-1.5.3rc2/fmriprep/data
copying fmriprep/data/__init__.py -> fmriprep-1.5.3rc2/fmriprep/data
$ python setup.py bdist_wheel | grep data
creating build/bdist.macosx-10.7-x86_64/wheel/fmriprep/data
creating build/bdist.macosx-10.7-x86_64/wheel/fmriprep/data/flirtsch
copying build/lib/fmriprep/data/flirtsch/bbr.sch -> build/bdist.macosx-10.7-x86_64/wheel/fmriprep/data/flirtsch
copying build/lib/fmriprep/data/sub-01_run-01_echo-3_bold.nii.gz -> build/bdist.macosx-10.7-x86_64/wheel/fmriprep/data
copying build/lib/fmriprep/data/sub-01_run-01_t2smap.nii.gz -> build/bdist.macosx-10.7-x86_64/wheel/fmriprep/data
copying build/lib/fmriprep/data/boilerplate.bib -> build/bdist.macosx-10.7-x86_64/wheel/fmriprep/data
copying build/lib/fmriprep/data/fmap-any_registration_testing.json -> build/bdist.macosx-10.7-x86_64/wheel/fmriprep/data
copying build/lib/fmriprep/data/itkIdentityTransform.txt -> build/bdist.macosx-10.7-x86_64/wheel/fmriprep/data
copying build/lib/fmriprep/data/reports-spec.yml -> build/bdist.macosx-10.7-x86_64/wheel/fmriprep/data
copying build/lib/fmriprep/data/fmap-any_registration.json -> build/bdist.macosx-10.7-x86_64/wheel/fmriprep/data
copying build/lib/fmriprep/data/susceptibility_syn.json -> build/bdist.macosx-10.7-x86_64/wheel/fmriprep/data
copying build/lib/fmriprep/data/fmap_atlas_2_MNI152NLin2009cAsym_affine.mat -> build/bdist.macosx-10.7-x86_64/wheel/fmriprep/data
copying build/lib/fmriprep/data/affine.json -> build/bdist.macosx-10.7-x86_64/wheel/fmriprep/data
copying build/lib/fmriprep/data/__init__.py -> build/bdist.macosx-10.7-x86_64/wheel/fmriprep/data
copying build/lib/fmriprep/data/sub-01_run-01_optcomb.nii.gz -> build/bdist.macosx-10.7-x86_64/wheel/fmriprep/data
copying build/lib/fmriprep/data/sub-01_run-01_echo-2_bold.nii.gz -> build/bdist.macosx-10.7-x86_64/wheel/fmriprep/data
copying build/lib/fmriprep/data/bids.json -> build/bdist.macosx-10.7-x86_64/wheel/fmriprep/data
copying build/lib/fmriprep/data/translation_rigid.json -> build/bdist.macosx-10.7-x86_64/wheel/fmriprep/data
copying build/lib/fmriprep/data/sub-01_run-01_echo-1_bold.nii.gz -> build/bdist.macosx-10.7-x86_64/wheel/fmriprep/data
copying build/lib/fmriprep/data/fmap_atlas.nii.gz -> build/bdist.macosx-10.7-x86_64/wheel/fmriprep/data
adding 'fmriprep/data/__init__.py'
adding 'fmriprep/data/affine.json'
adding 'fmriprep/data/bids.json'
adding 'fmriprep/data/boilerplate.bib'
adding 'fmriprep/data/fmap-any_registration.json'
adding 'fmriprep/data/fmap-any_registration_testing.json'
adding 'fmriprep/data/fmap_atlas.nii.gz'
adding 'fmriprep/data/fmap_atlas_2_MNI152NLin2009cAsym_affine.mat'
adding 'fmriprep/data/itkIdentityTransform.txt'
adding 'fmriprep/data/reports-spec.yml'
adding 'fmriprep/data/sub-01_run-01_echo-1_bold.nii.gz'
adding 'fmriprep/data/sub-01_run-01_echo-2_bold.nii.gz'
adding 'fmriprep/data/sub-01_run-01_echo-3_bold.nii.gz'
adding 'fmriprep/data/sub-01_run-01_optcomb.nii.gz'
adding 'fmriprep/data/sub-01_run-01_t2smap.nii.gz'
adding 'fmriprep/data/susceptibility_syn.json'
adding 'fmriprep/data/translation_rigid.json'
adding 'fmriprep/data/flirtsch/bbr.sch'
```

So the sdist is invalid, but fortunately we push pure Python wheels and everybody uses Docker, anyway. If I do:

```Diff
diff --git a/setup.cfg b/setup.cfg
index 6e8ef77f..fa173605 100644
--- a/setup.cfg
+++ b/setup.cfg
@@ -39,7 +39,6 @@ test_requires =
     codecov
     pytest
 packages = find:
-include_package_data = True
 
 [options.exclude_package_data]
 * = tests
```

Then:

**Comment by oesteban** [comment]
Fair enough

**Comment by effigies** [comment]
Shall I just push that change to `master`? It's quite small. If you'd rather have a PR, I can do that.

**Comment by oesteban** [comment]
Please send a PR to remove that `fmriprep/data/__init__.py` file.

**Comment by effigies** [comment]
Why do we want to remove that?

**Comment by oesteban** [comment]
Why is it necessary?

**Comment by effigies** [comment]
Hmm. Might not be. It makes `fmriprep.data` a package. I'll check to see if they still get included without.

**Comment by oesteban** [comment]
with the MANIFEST it seemed to work without the `__init__.py` so I guess it will still work without

**Pull request closed without merging**
