### PR TITLE
FIX: exclude "echo" entity from sdc reports

### PR DESCRIPTION
**Pull request by mgxd**
A test fix for #2150

### CODE REVIEW

**Comment by mgxd** [comment]
ok, things look right:
https://14291-53175327-gh.circle-artifacts.com/0/tmp/ds210/derivatives/fmriprep/sub-02.html

**Comment by oesteban** [comment]
Shouldn't this PR target `maint/20.1.x` ?

**Comment by mgxd** [comment]
We could (and probably should), but I don't think we've introduced any `20.1.x` breaking changes yet?

**Comment by oesteban** [comment]
Yup, a simple merge should do. I just realized that we need to start operating that way ASAP.

**Pull request merged**
