### PR TITLE
[FIX] Do not crash if all aroma components are classified as noise

### LINKED ISSUE #1300: Crash on AROMA if all ICs are classified as motion
The title says it all. For every functional run, out of hundreds, in which AROMA incidentally classified all ICs as being motion-related, FMRIPREP crashes.

It doesn't seem to be an issue with AROMA as fsl_regfilt works fine even in these cases. But somehow the workflow doesn't finish.

When I try to open the pklz crash reports with nipypecli, then nipypecli itself crashes too...

### PR DESCRIPTION
**Pull request by jdkent**
## Changes proposed in this pull request
fixes #1300 (changes the default behavior (no crash instead of crash) in case ICA-AROMA classifies everything as noise)
- deprecate `ignore-aroma-denoising-errors`
- add `--error-on-aroma-warnings`
- allow [aroma_confounds](https://github.com/jdkent/fmriprep/blob/8455b81ee9c1c3adc422a6b4b26aa13058c731a4/fmriprep/interfaces/confounds.py#L105) to be None
- add some logic to connecting workflows in case [aroma_confounds is None](https://github.com/jdkent/fmriprep/blob/2bcf9f75d19582c1adcc9c5be33464a022fafd4f/fmriprep/workflows/bold/base.py#L1068)

## Documentation that should be reviewed

TODO:
- add test to make sure the aroma confounds interface behaves as expected.

### CODE REVIEW

**Comment by jdkent** [comment]
[melodic keeps giving me an error](https://385-92465059-gh.circle-artifacts.com/0/tmp/ds054/work/fmriprep_wf/single_subject_100185_wf/func_preproc_task_machinegame_run_01_wf/ica_aroma_wf/melodic/_report/report.rst), possibly due to specifying too few components? I may test without specifying any restrictions on dimensionality to see if the error keeps up.

**Comment by jdkent** [comment]
ds054 does not appear to work with aroma.enabled, I'll look into it later today.

**Comment by jdkent** [comment]
I've decided to use the partial re-run for ds005, let me know if that is not appropriate.

During the re-run nipype appears to recognize that the hash is updates (the melodic command changed as expected)
```
Old/new hashes = 0cec2c01968bf7f679a8592d6586a968/65c07444309a097e76c632a159a1e7ed
190119-21:25:15,82 nipype.workflow VERBOSE:
	           Some dictionary entries had differing values:
            * dim: 1 != -200
            * in_files: [('/scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_mixedgamblestask_run_01_wf/ica_aroma_wf/smooth/vol0000_xform-00000_merged_cut_smooth.nii.gz', '2aea76f166554c8413bf313925105452')] != [['/scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_mixedgamblestask_run_01_wf/ica_aroma_wf/smooth/vol0000_xform-00000_merged_cut_smooth.nii.gz', '2aea76f166554c8413bf313925105452']]
190119-21:25:15,86 nipype.workflow INFO:
	 [Job 186] Cached (fmriprep_wf.single_subject_01_wf.func_preproc_task_mixedgamblestask_run_01_wf.ica_aroma_wf.bold_mni_trans_wf.bold_reference_wf.enhance_and_skullstrip_bold_wf.check_hdr).
190119-21:25:15,158 nipype.workflow INFO:
	 [Node] Setting-up "fmriprep_wf.single_subject_01_wf.func_preproc_task_mixedgamblestask_run_01_wf.ica_aroma_wf.melodic" in "/scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_mixedgamblestask_run_01_wf/ica_aroma_wf/melodic".
190119-21:25:15,158 nipype.workflow INFO:
	 [Node] Outdated cache found for "fmriprep_wf.single_subject_01_wf.func_preproc_task_mixedgamblestask_run_01_wf.ica_aroma_wf.melodic".
190119-21:25:15,167 nipype.workflow INFO:
	 [Node] Running "melodic" ("nipype.interfaces.fsl.model.MELODIC"), a CommandLine Interface with command:
melodic -i /scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_mixedgamblestask_run_01_wf/ica_aroma_wf/smooth/vol0000_xform-00000_merged_cut_smooth.nii.gz -d 1 -m /scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_mixedgamblestask_run_01_wf/ica_aroma_wf/bold_mni_trans_wf/mask_mni_tfm/ref_image_corrected_brain_mask_maths_trans.nii.gz --mmthresh=0.500000 --nobet -o /scratch/fmriprep_wf/single_subject_01_wf/func_preproc_task_mixedgamblestask_run_01_wf/ica_aroma_wf/melodic --Ostats --tr=2.000000
```

However, when I check the artifacts of the re-run, the [melodic command.txt](https://400-92465059-gh.circle-artifacts.com/0/tmp/ds005/work_partial/fmriprep_wf/single_subject_01_wf/func_preproc_task_mixedgamblestask_run_01_wf/ica_aroma_wf/melodic/command.txt) does not reflect the changed command. (e.g. it says `-d -200` instead of `-d 1`

I'm currently at a loss on what to check next. @oesteban @effigies any ideas off the top of your heads?

It may have to do with the nipype execution engine?

Otherwise my next test is just to run the commands locally and manually check the results.

**Comment by oesteban** [comment]
I'll look into this on Tuesday 👍

**Comment by jdkent** [comment]
Here is review of my findings and what I did to address them:

### finding 1:
- when [copying](https://github.com/poldracklab/fmriprep/blob/84672ee6e171d84f06bb271dbc7bb46d2b20cc2f/.circleci/config.yml#L427) work into work_partial, the [symlink that ica_aroma creates](https://github.com/maartenmennes/ICA-AROMA/blob/b53bd93c6cad34655d5bc122168351eeb6652e1c/ICA_AROMA_functions.py#L55) for the melodic directory still points to the original run of melodic.
  - so even if I were to change the parameters of how melodic was re-run, ica_aroma look in the previous melodic directory
### solution 1:
- delete the `ica_aroma_wf` directory entirely for the re-run

### finding 2:
- the re-run of fmriprep on ds005 uses the [work directory instead of work_partial](https://github.com/poldracklab/fmriprep/blob/84672ee6e171d84f06bb271dbc7bb46d2b20cc2f/.circleci/config.yml#L442)

### solution 2:
- change the working directory to `work_partial`

### finding 3:
- I cannot limit the melodic components to 1 since ica_aroma expects there to be a 4th dimension to the data, and if there is only 1 component, then the image is interpreted as 3 dimensional

### solution 3:
- limit the melodic components to 2 instead of 1.

### finding 4: 
- the first bold run, even when limited to 2 melodic components, did not classify both as noise

### solution 4:
- use the second bold run instead (they are both classified as noise)

### finding 5:
- if all the components are classified as noise, none of the components are added to the regressors file (this is expected behavior, but I wanted to make an explicit note of it)

### solution 5:
- I want to keep this behavior since if all the components are classified as noise, it should not be easy to use them as a regressor (like nothing went wrong). This helps people do the right thing (check their data!) without being as extreme as raising an error. This is the same behavior as if `--ignore-aroma-denoising-errors` was specified previously.

**Comment by oesteban** [comment]
This is looking good. As soon as tests pass, I'll be merging this. Thanks a lot for all this hard work @jdkent .

**Comment by oesteban** [comment]
Okay, I'm going to merge this:

aroma-warning

**Comment by jdkent** [comment]
That sounds good, and thank you for all your work and polish!

**Pull request merged**
