### PR TITLE
[FIX] Error releasing

### PR DESCRIPTION
**Pull request by oesteban**

### CODE REVIEW

**Comment by effigies** [comment]
Want to update the changelog, too?

**Comment by oesteban** [comment]
It's already there, this fixes #778 that needed to change after nipy/nipype#2237

**Comment by effigies** [comment]
? There's nothing in the changelog since rc6.

**Comment by oesteban** [comment]
Oh, gotcha. I'll include that in this PR :+1:

**Comment by oesteban** [comment]
(merge manually, for some reason github got confused)

**Comment by effigies** [comment]
I think you pushed the commits to oesteban/master, but pushed the tags to poldracklab.

**Comment by oesteban** [comment]
:S

**Pull request closed without merging**
