### PR TITLE
[RTM] ENH: Improve confound header names

### LINKED ISSUE #360: Add steady state detector
Preliminary code can be found in MRIQC (https://github.com/poldracklab/mriqc/blob/9667137e42dbb1c4c70172d4e18ba358c5761c86/mriqc/utils/misc.py#L46). Each non-steady state volume should be result in an "outlier regressor" ("1" for the volume and "0" everywhere else) in the _confounds file.  New columns could be names "NonSteadyStateOutlier0", "NonSteadyStateOutlier1 etc."

### PR DESCRIPTION
**Pull request by effigies**
See https://github.com/poldracklab/fmriprep/issues/360#issuecomment-319211238 and nipy/nipype#2136

Closes #360.

### CODE REVIEW

**Comment by effigies** [comment]
While that fixes it, there is an issue for datasets too short to produce confounds, but with non-steady-state outliers, such as `ds005/sub-01/func/*run-01*.bold`. Not sure how I missed this. There's a fix over at nipy/nipype#2138, which I've tested on that dataset locally.

I'll update the pins here, so that Circle will build it...

**Comment by oesteban** [comment]
Should I merge this already?

**Comment by effigies** [comment]
No.

**Comment by oesteban** [comment]
Understood!

**Comment by effigies** [comment]
Excerpted [confounds.tsv](https://682-78558509-gh.circle-artifacts.com/1/home/ubuntu/ds005/out/fmriprep/sub-01/func/sub-01_task-mixedgamblestask_run-01_bold_confounds.tsv):

tCompCor00 | tCompCor05 | aCompCor00 | aCompCor05 | NonSteadyStateOutlier00
-- | -- | -- | -- | --
0 | 0 | 0 | 0 | 1
-0.4371572005 | 0.0557365655 | -0.3931056217 | 0.2711029978 | 0
0.0644078063 | -0.5244772443 | 0.13139585 | -0.0393245026 | 0
0.3763848735 | 0.2411832222 | 0.2838979808 | -0.3508611558 | 0
0.3745648673 | -0.0766074055 | 0.2799187512 | -0.0620435332 | 0
0.1518852892 | 0.2507682694 | 0.3989339177 | 0.3213743293 | 0
-0.1056200975 | 0.1460221678 | 0.3054514479 | 0.2945456173 | 0
-0.0022437328 | -0.1199075195 | 0.2638761357 | -0.2511155202 | 0
0.3316998401 | -0.2322500403 | 0.1232900596 | -0.2069637969 | 0
0.1620694153 | 0.3295860188 | -0.0552770858 | 0.1250341463 | 0
-0.1316354992 | -0.1373579747 | -0.1013527616 | 0.5480407703 | 0
-0.5190575626 | 0.0931088749 | -0.3375762751 | -0.1050603748 | 0
-0.2409135032 | -0.0395117923 | -0.2651946021 | -0.1856786497 | 0
0.0516509609 | 0.3878416506 | -0.2130329332 | -0.0009426788 | 0
-0.0070883494 | -0.4582866366 | -0.1992427774 | 0.0164638213 | 0
-0.0689471074 | 0.084151844 | -0.221982086 | -0.3745714704 | 0

@oesteban @chrisfilo Do you want to have a look at the [whole file](https://682-78558509-gh.circle-artifacts.com/1/home/ubuntu/ds005/out/fmriprep/sub-01/func/sub-01_task-mixedgamblestask_run-01_bold_confounds.tsv) to see if there are any other things to fix up while we're playing around here?

**Comment by effigies** [comment]
Just a pin update. Taking nipype merge as go-ahead to merge.

**Pull request merged**
