### PR TITLE
RTM Don't use aCompCor for now

### PR DESCRIPTION
**Pull request by shoshber**
Because segmentation isn't good enough for it to be useful: https://github.com/poldracklab/fmriprep/issues/177

### CODE REVIEW

**Comment by chrisfilo** [comment]
I'm afraid that reverting this change when we decide to fix aCompCor will be complicated. If you are worried that users will accidentally use compcor why don't just comment out the lines linking it to the confounds concatenator? Adding a link to https://github.com/poldracklab/fmriprep/issues/177 above the commented lines would make the change more clear.

**Comment by rwblair** [comment]
LGTM

**Comment by shoshber** [comment]
why would reverting the commit be difficult? I prefer to rely on versioning to keep old code rather than commenting stuff out.

**Comment by chrisfilo** [comment]
Because other changes will be merged in the meantime and when you try to
revert this change you will run into a conflict.

**Comment by shoshber** [comment]
But it's the same if you comment stuff out, the commented code becomes out of date so quickly there's no point in keeping it in the file

**Pull request closed without merging**
