### PR TITLE
[RTM] Documentation

### PR DESCRIPTION
**Pull request by shoshber**

### CODE REVIEW

**Comment by shoshber** [comment]
This is what the documentation/site will look like once this PR is merged:

[html.zip](https://github.com/poldracklab/fmriprep/files/645369/html.zip)

**Comment by shoshber** [comment]
incorporated comments from yesterday. With the additional pictures the HTML is too big to upload a new zip.

**Comment by chrisfilo** [comment]
Great! One last thing I forgot to bring up yesterday - does the example report incorporate the latest changes: aCompCor ROIs and showing GM/WM boundary for EPI->T1 registration?

**Comment by shoshber** [comment]
Ah, it does not. Perhaps right before release we could upload a new sample report, since things will continue to change, right?

**Comment by chrisfilo** [comment]
Yes, you can delay it until the release if you want. Please open an issue
that the example report is currently outdated.

On Thu, Dec 15, 2016 at 1:51 PM, Shoshana Berleant <notifications@github.com

**Pull request merged**
