### PR TITLE
Update fmap.py : import _get_pe_index in get_ees

### LINKED ISSUE #983: interfaces.fmap.get_ees : _get_pe_index is not defined
In the same vein as #951 : 

I got this error running fmriprep on a phillips dataset without `EffectiveEchoSpacing` defined in the json : 

`NameError: name '_get_pe_index' is not defined`

`get_ees` is probably dynamically used as an interface in the workflows so we should import all the dependencies (http://nipype.readthedocs.io/en/latest/users/function_interface.html#using-external-packages)

Unless I missed something, it should be as simple as adding this line in the function :
```python
from fmriprep.interfaces.fmap import _get_pe_index
```

I can open a pull request if that make sense.

### PR DESCRIPTION
**Pull request by naveau**
Should fix #983

### CODE REVIEW

**Comment by naveau** [comment]
It's currently running on my dataset, the fmap step finished properly 👍 

```
[Node] Running "get_ees" ("niworkflows.nipype.interfaces.utility.wrappers.Function")
180214-13:27:27,500 workflow INFO:
[Node] Finished "fmriprep_wf.single_subject_026_wf.func_preproc_task_rest_wf.sdc_unwarp_wf.get_ees".
```

**Comment by effigies** [comment]
Excellent. Do you want to add yourself to the [Zenodo file](https://github.com/poldracklab/fmriprep/blob/master/.zenodo.json)?

**Comment by oesteban** [comment]
Hi @naveau, please let us know if you'd like to add your name to the zenodo file 👍

**Comment by naveau** [comment]
Hi @oesteban, @effigies,
Sry for the delay, I won't add my name in the list of the creators. Consider this short line of code as an humble bug fix from one of your new user.
Please keep up the good work on this project !

**Pull request merged**
