### PR TITLE
CI: Minor change to trigger builds

### PR DESCRIPTION
**Pull request by effigies**
Seeing if error in gh-1001 is hitting master

### CODE REVIEW

**Comment by mgxd** [comment]
@effigies same error is present in #1036 as well

**Comment by effigies** [comment]
@oesteban @emdupre Any notion as to why the ds210 tests are failing recently? We may need to upstream this bug to nibabel, but a minimal reproduction would be good to have first.

**Comment by effigies** [comment]
@mgxd I thought I'd seen this issue before. Apparently I commented on it there, too.

**Comment by emdupre** [comment]
I'm really not sure what triggered it to start failing&mdash; it does seem like an introduced dependency error to me, but only niworkflows cut a version recently.

I'll keep playing around with it in #1038 and try pinning the dependencies, but given that [we don't even have STC implemented for multi-echo](https://github.com/poldracklab/fmriprep/blame/83c4f1e0682b788cc1bac7831b218d5bf322821f/fmriprep/workflows/bold/base.py#L270), I'm erring towards amending that check for now. WDYT?

**Comment by oesteban** [comment]
https://github.com/poldracklab/fmriprep/pull/1001#issuecomment-379034447

**Pull request closed without merging**
