### PR TITLE
REF: Separate sdcflows from fMRIPrep

### PR DESCRIPTION
**Pull request by oesteban**
## Changes proposed in this pull request

Splits the susceptibility distortion correction (SDC) workflows out to https://github.com/sdcflows

## Documentation that should be reviewed

- The SDC workflows section and their API.
- The SDC-related reportlets are present and render exactly the same as they did before the split.

### CODE REVIEW

**Comment by oesteban** [comment]
This is looking better - [master/ds054](https://9268-53175327-gh.circle-artifacts.com/0/tmp/ds054/derivatives/fmriprep/sub-100185.html) vs [branch/d054](https://4020-53608443-gh.circle-artifacts.com/0/tmp/ds054/derivatives/fmriprep/sub-100185.html). ds005 (syn) looks good too.

**Comment by oesteban** [comment]
@mattcieslak after merging this, all the SDC routines will be outsourced from fMRIPrep. Do you want to have a look, review this PR and see how you can now import and use SDCflows?

**Comment by mattcieslak** [comment]
This looks great! I'll use a similar approach in qsiprep

**Comment by oesteban** [comment]
I'll merge after updating the sdcflows pin to a release.

**Pull request merged**
