### PR TITLE
[WIP, FIX] remove bold_mask generation from t2s

### PR DESCRIPTION
**Pull request by emdupre**
## Changes proposed in this pull request

Addresses #1786  

Removes `bold_mask` generation from `bold_t2s_wf` in the case of multi-echo data. 

## Documentation that should be reviewed

N/A.

### CODE REVIEW

**Comment by emdupre** [comment]
This code is passing locally, and it seems like the errors here are in the cache:

```python traceback
FileNotFoundError: [Errno 2] No such file or directory: 'result_csf_msk.pklz'
```
or due to build time-out:

```python traceback
Too long with no output (exceeded 2h0m0s)
```

I'll try to clear the cache and re-run.

**Comment by effigies** [comment]
@emdupre I'm not sure this is a cache issue. Can you try updating the nipype requirement in setup.cfg to:

```
nipype @ git+https://github.com/effigies/nipype.git@e206f3d53198c683e959fe1e73426ce5cf362b93
```

**Comment by emdupre** [comment]
Thanks for the pin, @effigies ! That worked perfectly :+1: 

The brain masks here for ds210 [don't look great](https://9863-53175327-gh.circle-artifacts.com/0/tmp/ds210/derivatives/fmriprep/sub-02.html), but they do locally for some data @Shotgunosine shared. Should I run (a non-downsampled) ds210 locally as well to confirm ?

**Comment by effigies** [comment]
@emdupre Yeah, I would go ahead and check on full-resolution (though you might want to truncate to ~40 TRs to save time).

**Comment by Shotgunosine** [comment]
Yeah, those maps do look problematic, hopefully they'll look better on full resolution. It looks like it's mostly including skull as opposed to excluding brain, which is a less drastic error I think.

**Comment by effigies** [comment]
@emdupre I merged master, so you'll want to `pull` before doing anything else. Feel free to rebase, if you'd rather not have the pin and merge in the history,

**Comment by emdupre** [comment]
Superceded by #2109

**Pull request closed without merging**
