### PR TITLE
[ENH,WIP] Filter warnings and print summary in the end

### LINKED ISSUE #840: Affines Do not Match
Hello, 

I'm seeing this set of error after running fmriprep on this dataset on openneuro: https://openneuro.org/datasets/ds001033/versions/00001?app=FMRIPREP&version=32&job=f0e26bac-f9ec-4c3c-a176-358d9ef4bbef

There seems to be a change in 'affine_transform' as indicated in the error logs. 

screen shot 2017-11-20 at 8 22 25 am

### PR DESCRIPTION
**Pull request by oesteban**
This filter should keep the `Affines of input and reference images do not match, CopyXForm will probably make the input image useless.` message under control.

Closes #840.

### CODE REVIEW

**Comment by effigies** [comment]
Is the warning useful to keep around? It seems to be empirically false.

**Comment by oesteban** [comment]
Yep, but I'd say the filter is still useful, DYT?

On Nov 16, 2017 12:37, "Chris Markiewicz" <notifications@github.com> wrote:

Is the warning useful to keep around? It seems to be empirically false.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/poldracklab/fmriprep/pull/837#issuecomment-345054934>,
or mute the thread

**Comment by effigies** [comment]
Could be. What warnings do we get multiple times?

**Comment by oesteban** [comment]
Hold on, this does not seem to be working.

**Comment by oesteban** [comment]
I'll close this for now. We can always come back if we consider it again.

**Pull request closed without merging**
